version: '3.8'

services:
  flowwright:
    image: flowright:latest
    ipc: host
    privileged: true
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      # persist runtime data and DBs on host
      - ./webapp/data:/app/webapp/data
      - ./webapp/databases:/app/webapp/databases
      - ./webapp/runs:/app/webapp/runs
      - ./webapp/steps:/app/webapp/steps
      - ./webapp/objects:/app/webapp/objects
      - ./webapp/files:/app/webapp/files
      - ./keywords:/app/keywords
    restart: unless-stopped
    shm_size: 2g
    mem_limit: 16g
    cpus: "4.0"
    tty: true
